/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TPeriod } from '../partials/Period';

export type TAccountGuarantor = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    party: TReference;
    onHold?: Boolean;
    period?: TPeriod;
};

