// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';

export type TBackboneElement = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
};

