/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TPeriod } from '../partials/Period';

export type TCitationStatusDate1 = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    activity: TCodeableConcept;
    actual?: Boolean;
    period: TPeriod;
};

