/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableReference } from '../partials/CodeableReference';
import { TReference } from '../partials/Reference';
import { TClinicalUseDefinitionOtherTherapy } from '../partials/ClinicalUseDefinitionOtherTherapy';

export type TClinicalUseDefinitionContraindication = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    diseaseSymptomProcedure?: TCodeableReference;
    diseaseStatus?: TCodeableReference;
    comorbidity?: TCodeableReference[];
    indication?: TReference[];
    otherTherapy?: TClinicalUseDefinitionOtherTherapy[];
};

