// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TClinicalUseDefinitionInteractant } from '../partials/ClinicalUseDefinitionInteractant';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TCodeableReference } from '../partials/CodeableReference';

export type TClinicalUseDefinitionInteraction = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    interactant?: TClinicalUseDefinitionInteractant[];
    type?: TCodeableConcept;
    effect?: TCodeableReference;
    incidence?: TCodeableConcept;
    management?: TCodeableConcept[];
};

