// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TCodeableConcept } from '../partials/CodeableConcept';

export type TContractContext = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    reference?: TReference;
    code?: TCodeableConcept[];
    text?: String;
};

