// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';
import { TCoding } from '../partials/Coding';

export type TContractSecurityLabel = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    number?: TUnsignedInt[];
    classification: TCoding;
    category?: TCoding[];
    control?: TCoding[];
};

