// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TPeriod } from '../partials/Period';
import { TCoverageEligibilityResponseItem } from '../partials/CoverageEligibilityResponseItem';

export type TCoverageEligibilityResponseInsurance = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    coverage: TReference;
    inforce?: Boolean;
    benefitPeriod?: TPeriod;
    item?: TCoverageEligibilityResponseItem[];
};

