// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';

export type TDataRequirementSort = {
    id?: String;
    extension?: TExtension[];
    path: String;
    direction: String;
};

