// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUri } from '../simpleTypes/Uri';
import { TBase64Binary } from '../simpleTypes/Base64Binary';

export type TDeviceUdiCarrier = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    deviceIdentifier?: String;
    issuer?: TUri;
    jurisdiction?: TUri;
    carrierAIDC?: TBase64Binary;
    carrierHRF?: String;
    entryType?: String;
};

