// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TQuantity } from '../partials/Quantity';
import { TRange } from '../partials/Range';

export type TDeviceRequestParameter = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    code?: TCodeableConcept;
    valueCodeableConcept?: TCodeableConcept;
    valueQuantity?: TQuantity;
    valueRange?: TRange;
    valueBoolean?: Boolean;
};

