/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TAttachment } from '../partials/Attachment';
import { TCoding } from '../partials/Coding';

export type TDocumentReferenceContent = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    attachment: TAttachment;
    format?: TCoding;
};

