/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TInt } from '../simpleTypes/Int';

export type TEncounterDiagnosis = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    condition: TReference;
    use?: TCodeableConcept;
    rank?: TInt;
};

