// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TPeriod } from '../partials/Period';

export type TEncounterStatusHistory = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    status: String;
    period: TPeriod;
};

