/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TQuantity } from '../partials/Quantity';
import { TRange } from '../partials/Range';

export type TEvidenceVariable = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    variableDefinition: TReference;
    handling?: String;
    valueCategory?: TCodeableConcept[];
    valueQuantity?: TQuantity[];
    valueRange?: TRange[];
};

