// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TExampleScenarioStep } from '../partials/ExampleScenarioStep';

export type TExampleScenarioAlternative = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    title: String;
    description?: TMarkdown;
    step?: TExampleScenarioStep[];
};

