// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TMeasurePopulation } from '../partials/MeasurePopulation';
import { TMeasureStratifier } from '../partials/MeasureStratifier';

export type TMeasureGroup = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    code?: TCodeableConcept;
    description?: String;
    population?: TMeasurePopulation[];
    stratifier?: TMeasureStratifier[];
};

