// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';

export type TMedicationRequestSubstitution = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    allowedBoolean?: Boolean;
    allowedCodeableConcept?: TCodeableConcept;
    reason?: TCodeableConcept;
};

