/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableReference } from '../partials/CodeableReference';
import { TPeriod } from '../partials/Period';
import { TReference } from '../partials/Reference';
import { TCodeableConcept } from '../partials/CodeableConcept';

export type TMedicinalProductDefinitionOperation = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    type?: TCodeableReference;
    effectiveDate?: TPeriod;
    organization?: TReference[];
    confidentialityIndicator?: TCodeableConcept;
};

