// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableReference } from '../partials/CodeableReference';
import { TRatio } from '../partials/Ratio';

export type TNutritionProductNutrient = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    item?: TCodeableReference;
    amount?: TRatio[];
};

