// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TRange } from '../partials/Range';
import { TCodeableConcept } from '../partials/CodeableConcept';

export type TObservationDefinitionQualifiedInterval = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    category?: String;
    range?: TRange;
    context?: TCodeableConcept;
    appliesTo?: TCodeableConcept[];
    gender?: String;
    age?: TRange;
    gestationalAge?: TRange;
    condition?: String;
};

