// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TExpression } from '../partials/Expression';

export type TPlanDefinitionCondition = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    kind: String;
    expression?: TExpression;
};

