// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TRange } from '../partials/Range';
import { TCodeableConcept } from '../partials/CodeableConcept';

export type TPopulation = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    ageRange?: TRange;
    ageCodeableConcept?: TCodeableConcept;
    gender?: TCodeableConcept;
    race?: TCodeableConcept;
    physiologicalCondition?: TCodeableConcept;
};

