// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TDecimal } from '../simpleTypes/Decimal';
import { TUri } from '../simpleTypes/Uri';

export type TQuantity = {
    id?: String;
    extension?: TExtension[];
    value?: TDecimal;
    comparator?: String;
    unit?: String;
    system?: TUri;
    code?: String;
};

