/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TAnnotation } from '../partials/Annotation';

export type TRiskEvidenceSynthesisCertaintySubcomponent = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    type?: TCodeableConcept;
    rating?: TCodeableConcept[];
    note?: TAnnotation[];
};

