// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';

export type TStructureDefinitionContext = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    type: String;
    expression: String;
};

