// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TQuantity } from '../partials/Quantity';

export type TSubstanceDefinitionMolecularWeight = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    method?: TCodeableConcept;
    type?: TCodeableConcept;
    amount: TQuantity;
};

