/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TSubstanceSpecificationIsotope } from '../partials/SubstanceSpecificationIsotope';
import { TSubstanceSpecificationMolecularWeight } from '../partials/SubstanceSpecificationMolecularWeight';
import { TReference } from '../partials/Reference';
import { TSubstanceSpecificationRepresentation } from '../partials/SubstanceSpecificationRepresentation';

export type TSubstanceSpecificationStructure = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    stereochemistry?: TCodeableConcept;
    opticalActivity?: TCodeableConcept;
    molecularFormula?: String;
    molecularFormulaByMoiety?: String;
    isotope?: TSubstanceSpecificationIsotope[];
    molecularWeight?: TSubstanceSpecificationMolecularWeight;
    source?: TReference[];
    representation?: TSubstanceSpecificationRepresentation[];
};

