/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUri } from '../simpleTypes/Uri';

export type TSubscriptionTopicNotificationShape = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    resource: TUri;
    include?: String[];
    revInclude?: String[];
};

