/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TSubstanceAmount } from '../partials/SubstanceAmount';

export type TSubstancePolymerStartingMaterial = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    material?: TCodeableConcept;
    type?: TCodeableConcept;
    isDefining?: Boolean;
    amount?: TSubstanceAmount;
};

