/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TTestReportAction2 } from '../partials/TestReportAction2';

export type TTestReportTeardown = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    action: TTestReportAction2[];
};

