/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

import { TExtension } from '../partials/Extension';
import { TTestScriptAction2 } from '../partials/TestScriptAction2';

export type TTestScriptTeardown = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    action: TTestScriptAction2[];
};

