version: '3'

services:
  app:
    build: .
    environment:
      PORT: 5051
      REACT_APP_AUTH_CUSTOM_USERNAME: "cognito:username,preferred_username"
      REACT_APP_AUTH_CUSTOM_GROUP: "cognito:groups,groups"
      REACT_APP_AUTH_CUSTOM_SCOPE: "custom:scope"
      REACT_APP_FHIR_SERVER_URL: 'http://localhost:3000'
      REACT_APP_AUTH_CODE_FLOW_CLIENT_ID: '0oarf29h6x2DaWCkT697'
      REACT_APP_AUTH_CODE_FLOW_AUTHORIZE_URL: 'https://icanbwell.okta.com/oauth2/v1/authorize'
      REACT_APP_AUTH_CODE_FLOW_TOKEN_URL: 'https://icanbwell.okta.com/oauth2/v1/token'
      REACT_APP_AUTH_CODE_FLOW_REDIRECT_URL: 'http://localhost:5051/authcallback'
      REACT_APP_AUTH_CODE_FLOW_LOGOUT_URL: 'https://icanbwell.okta.com/oauth2/v1/logout'
      REACT_APP_AUTH_WELL_KNOWN_URL: 'https://icanbwell.okta.com/.well-known/openid-configuration'
      REACT_APP_TOKEN_TO_SEND_TO_FHIR_SERVER: 'id_token' # other option is `jwt'
      REACT_APP_AUTH_OKTA_CODE_FLOW_CLIENT_ID: '0oarf29h6x2DaWCkT697'
      REACT_APP_AUTH_OKTA_AUTHORIZE_URL: 'https://icanbwell.okta.com/oauth2/v1/authorize'
      REACT_APP_AUTH_OKTA_TOKEN_URL: 'https://icanbwell.okta.com/oauth2/v1/token'
      REACT_APP_AUTH_OKTA__REDIRECT_URL: 'http://localhost:5051/authcallback'
      REACT_APP_AUTH_OKTA_LOGOUT_URL: 'https://icanbwell.okta.com/oauth2/v1/logout'
      REACT_APP_AUTH_OKTA_WELL_KNOWN_URL: 'https://icanbwell.okta.com/.well-known/openid-configuration'
      REACT_APP_AUTH_OKTA_TOKEN_TO_SEND_TO_FHIR_SERVER: 'id_token' # other option is `jwt'
    ports:
      - "5051:5051"
    volumes:
      - ./src:/app/src/
      - ./public:/app/public/
    command: yarn start
