services:
  app:
    build: .
    environment:
      PORT: 5051
      REACT_APP_VERSION: 'local'
      REACT_APP_FHIR_SERVER_URL: 'http://localhost:3000'
      REACT_APP_AWS_REGION: 'us-east-1'
      # list of AuthProviders
      REACT_APP_AUTH_PROVIDERS: 'cognito'
      # Each AuthProvider has its own set of environment variables
      REACT_APP_AUTH_COGNITO_CUSTOM_USERNAME: 'cognito:username'
      REACT_APP_AUTH_COGNITO_CUSTOM_GROUP: 'cognito:groups'
      REACT_APP_AUTH_COGNITO_CUSTOM_SCOPE: 'custom:scope'
      REACT_APP_AUTH_COGNITO_CLIENT_ID: 'fhir-ui'
      REACT_APP_AUTH_COGNITO_REDIRECT_URL: 'http://localhost:5051/authcallback'
      REACT_APP_AUTH_COGNITO_WELL_KNOWN_URL: 'http://localhost:8080/realms/master/.well-known/openid-configuration'
      REACT_APP_AUTH_COGNITO_TOKEN_TO_SEND_TO_FHIR_SERVER: 'jwt' # other option is 'id_token'
      REACT_APP_AUTH_COGNITO_TOKEN_FOR_USER_DETAILS: 'jwt'
      # To configure Okta, uncomment the following lines and set the appropriate values
      # and add 'okta' to REACT_APP_AUTH_PROVIDERS
      # 
      # REACT_APP_AUTH_OKTA_CUSTOM_USERNAME: 'preferred_username'
      # REACT_APP_AUTH_OKTA_CUSTOM_GROUP: 'groups'
      # REACT_APP_AUTH_OKTA_CUSTOM_SCOPE: 'custom:scope'
      # REACT_APP_AUTH_OKTA_CLIENT_ID: ''
      # REACT_APP_AUTH_OKTA_REDIRECT_URL: 'http://localhost:5051/authcallback'
      # REACT_APP_AUTH_OKTA_WELL_KNOWN_URL: ''
      # REACT_APP_AUTH_OKTA_TOKEN_TO_SEND_TO_FHIR_SERVER: 'jwt'
      # REACT_APP_AUTH_OKTA_TOKEN_FOR_USER_DETAILS: 'id_token'
      # REACT_APP_AUTH_OKTA_REMOVE_SCOPE_PREFIX: ''
    ports:
      - '5051:5051'
    volumes:
      - ./src:/app/src/
      - ./public:/app/public/
    command: yarn start
