/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

/**
ActivityDefinition
    This resource allows for the definition of some activity to be performed,
    independent of a particular patient, practitioner, or other performance
    context.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { Typography } from '@mui/material';
import { TActivityDefinition } from '../../types/resources/ActivityDefinition';

// Import all the partial resource
import Partials from '../../partials';

const ActivityDefinition = ({ resource }: { resource: TActivityDefinition }): React.ReactElement => {
    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${resource.id}`}>
                {resource.resourceType}/{resource.id}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.url &&
                <Partials.Uri
                    uri={resource.url}
                    name='Url'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='url'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.experimental &&
                <Partials.Boolean
                    boolean={resource.experimental}
                    name='Experimental'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='experimental'
                />
            }
            {
                resource.subjectCodeableConcept &&
                <Partials.CodeableConcept
                    codeableConcept={resource.subjectCodeableConcept}
                    name='Subject Codeable Concept'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='subject-codeable-concept'
                />
            }
            {
                resource.subjectReference &&
                <Partials.Reference
                    reference={resource.subjectReference}
                    name='Subject Reference'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='subject-reference'
                />
            }
            {
                resource.date &&
                <Partials.DateTime
                    dateTime={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='date'
                />
            }
            {
                resource.description &&
                <Partials.Markdown
                    markdown={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='description'
                />
            }
            {
                resource.jurisdiction &&
                <Partials.CodeableConcept
                    codeableConcept={resource.jurisdiction}
                    name='Jurisdiction'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='jurisdiction'
                />
            }
            {
                resource.purpose &&
                <Partials.Markdown
                    markdown={resource.purpose}
                    name='Purpose'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='purpose'
                />
            }
            {
                resource.copyright &&
                <Partials.Markdown
                    markdown={resource.copyright}
                    name='Copyright'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='copyright'
                />
            }
            {
                resource.effectivePeriod &&
                <Partials.Period
                    period={resource.effectivePeriod}
                    name='Effective Period'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='effective-period'
                />
            }
            {
                resource.topic &&
                <Partials.CodeableConcept
                    codeableConcept={resource.topic}
                    name='Topic'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='topic'
                />
            }
            {
                resource.library &&
                <Partials.Canonical
                    canonical={resource.library}
                    name='Library'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='library'
                />
            }
            {
                resource.kind &&
                <Partials.Code code={resource.kind} name='Kind'/>
            }
            {
                resource.profile &&
                <Partials.Canonical
                    canonical={resource.profile}
                    name='Profile'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='profile'
                />
            }
            {
                resource.code &&
                <Partials.CodeableConcept
                    codeableConcept={resource.code}
                    name='Code'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='code'
                />
            }
            {
                resource.intent &&
                <Partials.Code code={resource.intent} name='Intent'/>
            }
            {
                resource.priority &&
                <Partials.Code code={resource.priority} name='Priority'/>
            }
            {
                resource.doNotPerform &&
                <Partials.Boolean
                    boolean={resource.doNotPerform}
                    name='Do Not Perform'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='do-not-perform'
                />
            }
            {
                resource.timingTiming &&
                <Partials.Timing
                    timing={resource.timingTiming}
                    name='Timing Timing'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='timing-timing'
                />
            }
            {
                resource.timingDateTime &&
                <Partials.DateTime
                    dateTime={resource.timingDateTime}
                    name='Timing Date Time'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='timing-date-time'
                />
            }
            {
                resource.timingAge &&
                <Partials.Quantity
                    quantity={resource.timingAge}
                    name='Timing Age'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='timing-age'
                />
            }
            {
                resource.timingPeriod &&
                <Partials.Period
                    period={resource.timingPeriod}
                    name='Timing Period'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='timing-period'
                />
            }
            {
                resource.timingDuration &&
                <Partials.Quantity
                    quantity={resource.timingDuration}
                    name='Timing Duration'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='timing-duration'
                />
            }
            {
                resource.location &&
                <Partials.Reference
                    reference={resource.location}
                    name='Location'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='location'
                />
            }
            {
                resource.productReference &&
                <Partials.Reference
                    reference={resource.productReference}
                    name='Product Reference'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='product-reference'
                />
            }
            {
                resource.productCodeableConcept &&
                <Partials.CodeableConcept
                    codeableConcept={resource.productCodeableConcept}
                    name='Product Codeable Concept'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='product-codeable-concept'
                />
            }
            {
                resource.quantity &&
                <Partials.Quantity
                    quantity={resource.quantity}
                    name='Quantity'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='quantity'
                />
            }
            {
                resource.dosage &&
                <Partials.Dosage
                    dosage={resource.dosage}
                    name='Dosage'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='dosage'
                />
            }
            {
                resource.bodySite &&
                <Partials.CodeableConcept
                    codeableConcept={resource.bodySite}
                    name='Body Site'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='body-site'
                />
            }
            {
                resource.specimenRequirement &&
                <Partials.Reference
                    reference={resource.specimenRequirement}
                    name='Specimen Requirement'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='specimen-requirement'
                />
            }
            {
                resource.observationRequirement &&
                <Partials.Reference
                    reference={resource.observationRequirement}
                    name='Observation Requirement'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='observation-requirement'
                />
            }
            {
                resource.observationResultRequirement &&
                <Partials.Reference
                    reference={resource.observationResultRequirement}
                    name='Observation Result Requirement'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='observation-result-requirement'
                />
            }
            {
                resource.transform &&
                <Partials.Canonical
                    canonical={resource.transform}
                    name='Transform'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='transform'
                />
            }
        </>
    );
};

export default ActivityDefinition;
