/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

/**
ResearchSubject
    A physical entity which is the primary unit of operational and/or
    administrative interest in a study.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from '@mui/material';

// Import all the partial resource
import Partials from '../../partials';

const ResearchSubject = ({ resource }) => {
  return (
    <>
      <Link
        title="Direct link to Resource"
        href={`/4_0_0/${resource.resourceType}/${resource.id}`}
      >
        {resource.resourceType}/{resource.id}
      </Link>
      {resource.meta && (
        <Partials.Meta
          meta={resource.meta}
          name="Meta"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="meta"
        />
      )}
      {resource.implicitRules && (
        <Partials.Uri
          uri={resource.implicitRules}
          name="Implicit Rules"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="implicit-rules"
        />
      )}
      {resource.language && (
        <Partials.Code code={resource.language} name="Language" />
      )}
      {resource.text && (
        <Partials.Narrative
          narrative={resource.text}
          name="Text"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="text"
        />
      )}
      {resource.extension && (
        <Partials.Extension
          extension={resource.extension}
          name="Extension"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="extension"
        />
      )}
      {resource.modifierExtension && (
        <Partials.Extension
          extension={resource.modifierExtension}
          name="Modifier Extension"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="modifier-extension"
        />
      )}
      {resource.identifier && (
        <Partials.Identifier
          identifier={resource.identifier}
          name="Identifier"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="identifier"
        />
      )}
      {resource.status && (
        <Partials.Code code={resource.status} name="Status" />
      )}
      {resource.period && (
        <Partials.Period
          period={resource.period}
          name="Period"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="period"
        />
      )}
      {resource.study && (
        <Partials.Reference
          reference={resource.study}
          name="Study"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="study"
        />
      )}
      {resource.individual && (
        <Partials.Reference
          reference={resource.individual}
          name="Individual"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="individual"
        />
      )}
      {resource.consent && (
        <Partials.Reference
          reference={resource.consent}
          name="Consent"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="consent"
        />
      )}
    </>
  );
};

export default ResearchSubject;
