/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

/**
SupplyDelivery
    Record of delivery of what is supplied.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from '@mui/material';

// Import all the partial resource
import Partials from '../../partials';

const SupplyDelivery = ({ resource }) => {
  return (
    <>
      <Link
        title="Direct link to Resource"
        href={`/4_0_0/${resource.resourceType}/${resource.id}`}
      >
        {resource.resourceType}/{resource.id}
      </Link>
      {resource.meta && (
        <Partials.Meta
          meta={resource.meta}
          name="Meta"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="meta"
        />
      )}
      {resource.implicitRules && (
        <Partials.Uri
          uri={resource.implicitRules}
          name="Implicit Rules"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="implicit-rules"
        />
      )}
      {resource.language && (
        <Partials.Code code={resource.language} name="Language" />
      )}
      {resource.text && (
        <Partials.Narrative
          narrative={resource.text}
          name="Text"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="text"
        />
      )}
      {resource.extension && (
        <Partials.Extension
          extension={resource.extension}
          name="Extension"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="extension"
        />
      )}
      {resource.modifierExtension && (
        <Partials.Extension
          extension={resource.modifierExtension}
          name="Modifier Extension"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="modifier-extension"
        />
      )}
      {resource.identifier && (
        <Partials.Identifier
          identifier={resource.identifier}
          name="Identifier"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="identifier"
        />
      )}
      {resource.basedOn && (
        <Partials.Reference
          reference={resource.basedOn}
          name="Based On"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="based-on"
        />
      )}
      {resource.partOf && (
        <Partials.Reference
          reference={resource.partOf}
          name="Part Of"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="part-of"
        />
      )}
      {resource.status && (
        <Partials.Code code={resource.status} name="Status" />
      )}
      {resource.patient && (
        <Partials.Reference
          reference={resource.patient}
          name="Patient"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="patient"
        />
      )}
      {resource.type && (
        <Partials.CodeableConcept
          codeableConcept={resource.type}
          name="Type"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="type"
        />
      )}
      {resource.occurrenceDateTime && (
        <Partials.DateTime
          dateTime={resource.occurrenceDateTime}
          name="Occurrence Date Time"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="occurrence-date-time"
        />
      )}
      {resource.occurrencePeriod && (
        <Partials.Period
          period={resource.occurrencePeriod}
          name="Occurrence Period"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="occurrence-period"
        />
      )}
      {resource.occurrenceTiming && (
        <Partials.Timing
          timing={resource.occurrenceTiming}
          name="Occurrence Timing"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="occurrence-timing"
        />
      )}
      {resource.supplier && (
        <Partials.Reference
          reference={resource.supplier}
          name="Supplier"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="supplier"
        />
      )}
      {resource.destination && (
        <Partials.Reference
          reference={resource.destination}
          name="Destination"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="destination"
        />
      )}
      {resource.receiver && (
        <Partials.Reference
          reference={resource.receiver}
          name="Receiver"
          resourceType={resource.resourceType}
          id={resource.id}
          searchParameter="receiver"
        />
      )}
    </>
  );
};

export default SupplyDelivery;
