/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

import { TId } from '../simpleTypes/Id';
import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCanonical } from '../simpleTypes/Canonical';
import { TReference } from '../partials/Reference';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from '../partials/Period';
import { TTiming } from '../partials/Timing';
import { TChargeItemPerformer } from '../partials/ChargeItemPerformer';
import { TQuantity } from '../partials/Quantity';
import { TDecimal } from '../simpleTypes/Decimal';
import { TMoney } from '../partials/Money';
import { TAnnotation } from '../partials/Annotation';

export type TChargeItem = {
    resourceType?: String;
    id?: TId;
    meta?: TMeta;
    implicitRules?: TUri;
    language?: String;
    text?: TNarrative;
    contained?: TResourceContainer[];
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    identifier?: TIdentifier[];
    definitionUri?: TUri[];
    definitionCanonical?: TCanonical[];
    status: String;
    partOf?: TReference[];
    code: TCodeableConcept;
    subject: TReference;
    context?: TReference;
    occurrenceDateTime?: TDateTime;
    occurrencePeriod?: TPeriod;
    occurrenceTiming?: TTiming;
    performer?: TChargeItemPerformer[];
    performingOrganization?: TReference;
    requestingOrganization?: TReference;
    costCenter?: TReference;
    quantity?: TQuantity;
    bodysite?: TCodeableConcept[];
    factorOverride?: TDecimal;
    priceOverride?: TMoney;
    overrideReason?: String;
    enterer?: TReference;
    enteredDate?: TDateTime;
    reason?: TCodeableConcept[];
    service?: TReference[];
    productReference?: TReference;
    productCodeableConcept?: TCodeableConcept;
    account?: TReference[];
    note?: TAnnotation[];
    supportingInformation?: TReference[];
};

