// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TQuantity } from '../partials/Quantity';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TPackagedProductDefinitionLegalStatusOfSupply } from '../partials/PackagedProductDefinitionLegalStatusOfSupply';
import { TMarketingStatus } from '../partials/MarketingStatus';
import { TPackagedProductDefinitionPackage } from '../partials/PackagedProductDefinitionPackage';

export type TPackagedProductDefinition = {
    resourceType?: String;
    id?: String;
    meta?: TMeta;
    implicitRules?: TUri;
    language?: String;
    text?: TNarrative;
    contained?: TResourceContainer[];
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    identifier?: TIdentifier[];
    name?: String;
    type?: TCodeableConcept;
    packageFor?: TReference[];
    status?: TCodeableConcept;
    statusDate?: TDateTime;
    containedItemQuantity?: TQuantity[];
    description?: TMarkdown;
    legalStatusOfSupply?: TPackagedProductDefinitionLegalStatusOfSupply[];
    marketingStatus?: TMarketingStatus[];
    characteristic?: TCodeableConcept[];
    copackagedIndicator?: Boolean;
    manufacturer?: TReference[];
    package?: TPackagedProductDefinitionPackage;
};

