/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { THumanName } from '../partials/HumanName';
import { TContactPoint } from '../partials/ContactPoint';
import { TDate } from '../simpleTypes/Date';
import { TAddress } from '../partials/Address';
import { TAttachment } from '../partials/Attachment';
import { TReference } from '../partials/Reference';
import { TPersonLink } from '../partials/PersonLink';

export type TPerson = {
    resourceType?: String;
    id?: String;
    meta?: TMeta;
    implicitRules?: TUri;
    language?: String;
    text?: TNarrative;
    contained?: TResourceContainer[];
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    identifier?: TIdentifier[];
    name?: THumanName[];
    telecom?: TContactPoint[];
    gender?: String;
    birthDate?: TDate;
    address?: TAddress[];
    photo?: TAttachment;
    managingOrganization?: TReference;
    active?: Boolean;
    link?: TPersonLink[];
};

