// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TReference } from '../partials/Reference';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { THumanName } from '../partials/HumanName';
import { TContactPoint } from '../partials/ContactPoint';
import { TDate } from '../simpleTypes/Date';
import { TAddress } from '../partials/Address';
import { TAttachment } from '../partials/Attachment';
import { TPeriod } from '../partials/Period';
import { TRelatedPersonCommunication } from '../partials/RelatedPersonCommunication';

export type TRelatedPerson = {
    resourceType?: String;
    id?: String;
    meta?: TMeta;
    implicitRules?: TUri;
    language?: String;
    text?: TNarrative;
    contained?: TResourceContainer[];
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    identifier?: TIdentifier[];
    active?: Boolean;
    patient: TReference;
    relationship?: TCodeableConcept[];
    name?: THumanName[];
    telecom?: TContactPoint[];
    gender?: String;
    birthDate?: TDate;
    address?: TAddress[];
    photo?: TAttachment[];
    period?: TPeriod;
    communication?: TRelatedPersonCommunication[];
};

