// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TReference } from '../partials/Reference';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from '../partials/Period';
import { TRiskAssessmentPrediction } from '../partials/RiskAssessmentPrediction';
import { TAnnotation } from '../partials/Annotation';

export type TRiskAssessment = {
    resourceType?: String;
    id?: String;
    meta?: TMeta;
    implicitRules?: TUri;
    language?: String;
    text?: TNarrative;
    contained?: TResourceContainer[];
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    identifier?: TIdentifier[];
    basedOn?: TReference;
    parent?: TReference;
    status: String;
    method?: TCodeableConcept;
    code?: TCodeableConcept;
    subject: TReference;
    encounter?: TReference;
    occurrenceDateTime?: TDateTime;
    occurrencePeriod?: TPeriod;
    condition?: TReference;
    performer?: TReference;
    reasonCode?: TCodeableConcept[];
    reasonReference?: TReference[];
    basis?: TReference[];
    prediction?: TRiskAssessmentPrediction[];
    mitigation?: String;
    note?: TAnnotation[];
};

