// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TReference } from '../partials/Reference';
import { TAnnotation } from '../partials/Annotation';
import { TSubstanceDefinitionMoiety } from '../partials/SubstanceDefinitionMoiety';
import { TSubstanceDefinitionProperty } from '../partials/SubstanceDefinitionProperty';
import { TSubstanceDefinitionMolecularWeight } from '../partials/SubstanceDefinitionMolecularWeight';
import { TSubstanceDefinitionStructure } from '../partials/SubstanceDefinitionStructure';
import { TSubstanceDefinitionCode } from '../partials/SubstanceDefinitionCode';
import { TSubstanceDefinitionName } from '../partials/SubstanceDefinitionName';
import { TSubstanceDefinitionRelationship } from '../partials/SubstanceDefinitionRelationship';
import { TSubstanceDefinitionSourceMaterial } from '../partials/SubstanceDefinitionSourceMaterial';

export type TSubstanceDefinition = {
    resourceType?: String;
    id?: String;
    meta?: TMeta;
    implicitRules?: TUri;
    language?: String;
    text?: TNarrative;
    contained?: TResourceContainer[];
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    identifier?: TIdentifier[];
    version?: String;
    status?: TCodeableConcept;
    classification?: TCodeableConcept[];
    domain?: TCodeableConcept;
    grade?: TCodeableConcept[];
    description?: TMarkdown;
    informationSource?: TReference[];
    note?: TAnnotation[];
    manufacturer?: TReference[];
    supplier?: TReference[];
    moiety?: TSubstanceDefinitionMoiety[];
    property?: TSubstanceDefinitionProperty[];
    molecularWeight?: TSubstanceDefinitionMolecularWeight[];
    structure?: TSubstanceDefinitionStructure;
    code?: TSubstanceDefinitionCode[];
    name?: TSubstanceDefinitionName[];
    relationship?: TSubstanceDefinitionRelationship[];
    sourceMaterial?: TSubstanceDefinitionSourceMaterial;
};

