/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';
import { TTiming } from '../partials/Timing';
import { TDate } from '../simpleTypes/Date';
import { TVerificationResultPrimarySource } from '../partials/VerificationResultPrimarySource';
import { TVerificationResultAttestation } from '../partials/VerificationResultAttestation';
import { TVerificationResultValidator } from '../partials/VerificationResultValidator';

export type TVerificationResult = {
    resourceType?: String;
    id?: String;
    meta?: TMeta;
    implicitRules?: TUri;
    language?: String;
    text?: TNarrative;
    contained?: TResourceContainer[];
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    target?: TReference[];
    targetLocation?: String[];
    need?: TCodeableConcept;
    status: String;
    statusDate?: TDateTime;
    validationType?: TCodeableConcept;
    validationProcess?: TCodeableConcept[];
    frequency?: TTiming;
    lastPerformed?: TDateTime;
    nextScheduled?: TDate;
    failureAction?: TCodeableConcept;
    primarySource?: TVerificationResultPrimarySource[];
    attestation?: TVerificationResultAttestation;
    validator?: TVerificationResultValidator[];
};

