/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

import { TExtension } from '../partials/Extension';
import { TDecimal } from '../simpleTypes/Decimal';

export type TBundleSearch = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    mode?: String;
    score?: TDecimal;
};

