/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';

export type TLinkageItem = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    type: String;
    resource: TReference;
};

