/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

import { TExtension } from '../partials/Extension';

export type TOperationDefinitionOverload = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    parameterName?: String[];
    comment?: String;
};

