/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TSubstanceAmount } from '../partials/SubstanceAmount';

export type TSubstancePolymerDegreeOfPolymerisation = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    degree?: TCodeableConcept;
    amount?: TSubstanceAmount;
};

