/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TIdentifier } from '../partials/Identifier';
import { TQuantity } from '../partials/Quantity';

export type TSubstanceSpecificationMoiety = {
    id?: String;
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    role?: TCodeableConcept;
    identifier?: TIdentifier;
    name?: String;
    stereochemistry?: TCodeableConcept;
    opticalActivity?: TCodeableConcept;
    molecularFormula?: String;
    amountQuantity?: TQuantity;
    amountString?: String;
};

