// This file is auto-generated by generate_components so do not edit manually

/**
AuditEvent
    A record of an event made for purposes of maintaining a security log. Typical
    uses include detection of intrusion attempts and monitoring for inappropriate
    usage.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { TAuditEvent } from '../../types/resources/AuditEvent';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const AuditEvent = ({ resource }: { resource: TAuditEvent }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    const lastUpdated = resource?.meta?.lastUpdated;
    const queryString = `?date=ge${lastUpdated?.toString()}&date=le${lastUpdated?.toString()}`;
    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}${queryString}`}>
                {resource.resourceType}/{uuid}{queryString}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.type &&
                <Partials.Coding
                    coding={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.subtype &&
                <Partials.Coding
                    coding={resource.subtype}
                    name='Subtype'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subtype'
                />
            }
            {
                resource.action &&
                <Partials.Code code={resource.action} name='Action'/>
            }
            {
                resource.period &&
                <Partials.Period
                    period={resource.period}
                    name='Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='period'
                />
            }
            {
                resource.recorded &&
                <Partials.Instant
                    instant={resource.recorded}
                    name='Recorded'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='recorded'
                />
            }
            {
                resource.outcome &&
                <Partials.Code code={resource.outcome} name='Outcome'/>
            }
            {
                resource.purposeOfEvent &&
                <Partials.CodeableConcept
                    codeableConcept={resource.purposeOfEvent}
                    name='Purpose Of Event'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='purpose-of-event'
                />
            }
            {
                resource.source &&
                <Partials.Reference
                    reference={resource.source}
                    name='Source'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='source'
                    field='observer'
                />
            }
        </>
    );
};

export default AuditEvent;
