/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_components so do not edit manually

/**
Condition
    A clinical condition, problem, diagnosis, or other event, situation, issue, or
    clinical concept that has risen to a level of concern.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { Typography } from '@mui/material';
import { TCondition } from '../../types/resources/Condition';

// Import all the partial resource
import Partials from '../../partials';
import { SecurityTagSystem } from '../../utils/securityTagSystem';
import { generateUuidV5, isUuid } from '../../utils/uid.util';

const Condition = ({ resource }: { resource: TCondition }): React.ReactElement => {
    const sourceAssigningAuthority = resource?.meta?.security?.find(
        s => s.system === SecurityTagSystem.sourceAssigningAuthority
    )?.code;
    const uuid = resource.id && isUuid(`${resource.id}`) ?
        resource.id : generateUuidV5(`${resource.id}|${sourceAssigningAuthority}`);

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.clinicalStatus &&
                <Partials.CodeableConcept
                    codeableConcept={resource.clinicalStatus}
                    name='Clinical Status'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='clinical-status'
                />
            }
            {
                resource.verificationStatus &&
                <Partials.CodeableConcept
                    codeableConcept={resource.verificationStatus}
                    name='Verification Status'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='verification-status'
                />
            }
            {
                resource.category &&
                <Partials.CodeableConcept
                    codeableConcept={resource.category}
                    name='Category'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='category'
                />
            }
            {
                resource.severity &&
                <Partials.CodeableConcept
                    codeableConcept={resource.severity}
                    name='Severity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='severity'
                />
            }
            {
                resource.code &&
                <Partials.CodeableConcept
                    codeableConcept={resource.code}
                    name='Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='code'
                />
            }
            {
                resource.bodySite &&
                <Partials.CodeableConcept
                    codeableConcept={resource.bodySite}
                    name='Body Site'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='body-site'
                />
            }
            {
                resource.subject &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject'
                />
            }
            {
                resource.encounter &&
                <Partials.Reference
                    reference={resource.encounter}
                    name='Encounter'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='encounter'
                />
            }
            {
                resource.onsetDateTime &&
                <Partials.DateTime
                    dateTime={resource.onsetDateTime}
                    name='Onset Date Time'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='onset-date-time'
                />
            }
            {
                resource.onsetAge &&
                <Partials.Quantity
                    quantity={resource.onsetAge}
                    name='Onset Age'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='onset-age'
                />
            }
            {
                resource.onsetPeriod &&
                <Partials.Period
                    period={resource.onsetPeriod}
                    name='Onset Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='onset-period'
                />
            }
            {
                resource.abatementDateTime &&
                <Partials.DateTime
                    dateTime={resource.abatementDateTime}
                    name='Abatement Date Time'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='abatement-date-time'
                />
            }
            {
                resource.abatementAge &&
                <Partials.Quantity
                    quantity={resource.abatementAge}
                    name='Abatement Age'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='abatement-age'
                />
            }
            {
                resource.abatementPeriod &&
                <Partials.Period
                    period={resource.abatementPeriod}
                    name='Abatement Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='abatement-period'
                />
            }
            {
                resource.recordedDate &&
                <Partials.DateTime
                    dateTime={resource.recordedDate}
                    name='Recorded Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='recorded-date'
                />
            }
            {
                resource.recorder &&
                <Partials.Reference
                    reference={resource.recorder}
                    name='Recorder'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='recorder'
                />
            }
            {
                resource.asserter &&
                <Partials.Reference
                    reference={resource.asserter}
                    name='Asserter'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='asserter'
                />
            }
            {
                resource.note &&
                <Partials.Annotation
                    annotation={resource.note}
                    name='Note'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='note'
                />
            }
        </>
    );
};

export default Condition;
