/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_components so do not edit manually

/**
DocumentManifest
    A collection of documents compiled for a purpose together with metadata that
    applies to the collection.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { Typography } from '@mui/material';
import { TDocumentManifest } from '../../types/resources/DocumentManifest';

// Import all the partial resource
import Partials from '../../partials';

const DocumentManifest = ({ resource }: { resource: TDocumentManifest }): React.ReactElement => {
    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${resource.id}`}>
                {resource.resourceType}/{resource.id}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.masterIdentifier &&
                <Partials.Identifier
                    identifier={resource.masterIdentifier}
                    name='Master Identifier'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='master-identifier'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.type &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='type'
                />
            }
            {
                resource.subject &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='subject'
                />
            }
            {
                resource.created &&
                <Partials.DateTime
                    dateTime={resource.created}
                    name='Created'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='created'
                />
            }
            {
                resource.author &&
                <Partials.Reference
                    reference={resource.author}
                    name='Author'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='author'
                />
            }
            {
                resource.recipient &&
                <Partials.Reference
                    reference={resource.recipient}
                    name='Recipient'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='recipient'
                />
            }
            {
                resource.source &&
                <Partials.Uri
                    uri={resource.source}
                    name='Source'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='source'
                />
            }
            {
                resource.content &&
                <Partials.Reference
                    reference={resource.content}
                    name='Content'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='content'
                />
            }
        </>
    );
};

export default DocumentManifest;
