// This file is auto-generated by generate_components so do not edit manually

/**
EnrollmentRequest
    This resource provides the insurance enrollment details to the insurer
    regarding a specified coverage.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { TEnrollmentRequest } from '../../types/resources/EnrollmentRequest';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const EnrollmentRequest = ({ resource }: { resource: TEnrollmentRequest }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.created &&
                <Partials.DateTime
                    dateTime={resource.created}
                    name='Created'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='created'
                />
            }
            {
                resource.insurer &&
                <Partials.Reference
                    reference={resource.insurer}
                    name='Insurer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='insurer'
                />
            }
            {
                resource.provider &&
                <Partials.Reference
                    reference={resource.provider}
                    name='Provider'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='provider'
                />
            }
            {
                resource.candidate &&
                <Partials.Reference
                    reference={resource.candidate}
                    name='Candidate'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='candidate'
                />
            }
            {
                resource.coverage &&
                <Partials.Reference
                    reference={resource.coverage}
                    name='Coverage'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='coverage'
                />
            }
        </>
    );
};

export default EnrollmentRequest;
