/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_components so do not edit manually

/**
Invoice
    Invoice containing collected ChargeItems from an Account with calculated
    individual and total price for Billing purpose.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { TInvoice } from '../../types/resources/Invoice';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const Invoice = ({ resource }: { resource: TInvoice }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.type &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.subject &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject'
                />
            }
            {
                resource.recipient &&
                <Partials.Reference
                    reference={resource.recipient}
                    name='Recipient'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='recipient'
                />
            }
            {
                resource.date &&
                <Partials.DateTime
                    dateTime={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='date'
                />
            }
            {
                resource.participant &&
                <Partials.Reference
                    reference={resource.participant}
                    name='Participant'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='participant'
                    field='actor'
                />
            }
            {
                resource.issuer &&
                <Partials.Reference
                    reference={resource.issuer}
                    name='Issuer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='issuer'
                />
            }
            {
                resource.account &&
                <Partials.Reference
                    reference={resource.account}
                    name='Account'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='account'
                />
            }
            {
                resource.lineItem &&
                <Partials.InvoiceLineItem
                    invoiceLineItem={resource.lineItem}
                    name='Line Item'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='line-item'
                />
            }
            {
                resource.totalPriceComponent &&
                <Partials.InvoicePriceComponent
                    invoicePriceComponent={resource.totalPriceComponent}
                    name='Total Price Component'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='total-price-component'
                />
            }
            {
                resource.totalNet &&
                <Partials.Money
                    money={resource.totalNet}
                    name='Total Net'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='total-net'
                />
            }
            {
                resource.totalGross &&
                <Partials.Money
                    money={resource.totalGross}
                    name='Total Gross'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='total-gross'
                />
            }
            {
                resource.paymentTerms &&
                <Partials.Markdown
                    markdown={resource.paymentTerms}
                    name='Payment Terms'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment-terms'
                />
            }
            {
                resource.note &&
                <Partials.Annotation
                    annotation={resource.note}
                    name='Note'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='note'
                />
            }
        </>
    );
};

export default Invoice;
