/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_components so do not edit manually

/**
Location
    Details and position information for a physical place where services are
    provided and resources and participants may be stored, found, contained, or
    accommodated.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { Typography } from '@mui/material';
import { TLocation } from '../../types/resources/Location';

// Import all the partial resource
import Partials from '../../partials';

const Location = ({ resource }: { resource: TLocation }): React.ReactElement => {
    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${resource.id}`}>
                {resource.resourceType}/{resource.id}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.operationalStatus &&
                <Partials.Coding
                    coding={resource.operationalStatus}
                    name='Operational Status'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='operational-status'
                />
            }
            {
                resource.mode &&
                <Partials.Code code={resource.mode} name='Mode'/>
            }
            {
                resource.type &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='type'
                />
            }
            {
                resource.telecom &&
                <Partials.ContactPoint
                    contactPoint={resource.telecom}
                    name='Telecom'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='telecom'
                />
            }
            {
                resource.address &&
                <Partials.Address
                    address={resource.address}
                    name='Address'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='address'
                />
            }
            {
                resource.physicalType &&
                <Partials.CodeableConcept
                    codeableConcept={resource.physicalType}
                    name='Physical Type'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='physical-type'
                />
            }
            {
                resource.managingOrganization &&
                <Partials.Reference
                    reference={resource.managingOrganization}
                    name='Managing Organization'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='managing-organization'
                />
            }
            {
                resource.partOf &&
                <Partials.Reference
                    reference={resource.partOf}
                    name='Part Of'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='part-of'
                />
            }
            {
                resource.endpoint &&
                <Partials.Reference
                    reference={resource.endpoint}
                    name='Endpoint'
                    resourceType={resource.resourceType}
                    id={resource.id}
                    searchParameter='endpoint'
                />
            }
            <Typography variant="h4" sx={{ mt: 1 }}>
                Related Resources
            </Typography>
            <Partials.ReverseReference
                name="PractitionerRole"
                id={resource.id}
                resourceType={resource.resourceType}
                reverseReferences={[{'target': 'PractitionerRole', 'property': 'location'}]}
            />
            <Partials.ReverseReference
                name="HealthcareService"
                id={resource.id}
                resourceType={resource.resourceType}
                reverseReferences={[{'target': 'HealthcareService', 'property': 'location'}]}
            />
            <Partials.ReverseReference
                name="Organization"
                id={resource.id}
                resourceType={resource.resourceType}
                reverseReferences={[{'target': 'Organization', 'property': 'location'}]}
            />
            <Partials.ReverseReference
                name="Schedule"
                id={resource.id}
                resourceType={resource.resourceType}
                reverseReferences={[{'target': 'Schedule', 'property': 'location'}]}
            />
        </>
    );
};

export default Location;
