/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_components so do not edit manually

/**
MedicinalProductIndication
    Indication for the Medicinal Product.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { Typography } from '@mui/material';
import { TMedicinalProductIndication } from '../../types/resources/MedicinalProductIndication';

// Import all the partial resource
import Partials from '../../partials';
import { SecurityTagSystem } from '../../utils/securityTagSystem';
import { generateUuidV5, isUuid } from '../../utils/uid.util';

const MedicinalProductIndication = ({ resource }: { resource: TMedicinalProductIndication }): React.ReactElement => {
    const sourceAssigningAuthority = resource?.meta?.security?.find(
        s => s.system === SecurityTagSystem.sourceAssigningAuthority
    )?.code;
    const uuid = resource.id && isUuid(`${resource.id}`) ?
        resource.id : generateUuidV5(`${resource.id}|${sourceAssigningAuthority}`);

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.subject &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject'
                />
            }
            {
                resource.diseaseSymptomProcedure &&
                <Partials.CodeableConcept
                    codeableConcept={resource.diseaseSymptomProcedure}
                    name='Disease Symptom Procedure'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='disease-symptom-procedure'
                />
            }
            {
                resource.diseaseStatus &&
                <Partials.CodeableConcept
                    codeableConcept={resource.diseaseStatus}
                    name='Disease Status'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='disease-status'
                />
            }
            {
                resource.comorbidity &&
                <Partials.CodeableConcept
                    codeableConcept={resource.comorbidity}
                    name='Comorbidity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='comorbidity'
                />
            }
            {
                resource.intendedEffect &&
                <Partials.CodeableConcept
                    codeableConcept={resource.intendedEffect}
                    name='Intended Effect'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='intended-effect'
                />
            }
            {
                resource.duration &&
                <Partials.Quantity
                    quantity={resource.duration}
                    name='Duration'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='duration'
                />
            }
            {
                resource.undesirableEffect &&
                <Partials.Reference
                    reference={resource.undesirableEffect}
                    name='Undesirable Effect'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='undesirable-effect'
                />
            }
        </>
    );
};

export default MedicinalProductIndication;
