/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_components so do not edit manually

/**
PackagedProductDefinition
    A medically related item or items, in a container or package.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { TPackagedProductDefinition } from '../../types/resources/PackagedProductDefinition';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const PackagedProductDefinition = ({ resource }: { resource: TPackagedProductDefinition }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.type &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.packageFor &&
                <Partials.Reference
                    reference={resource.packageFor}
                    name='Package For'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='package-for'
                />
            }
            {
                resource.status &&
                <Partials.CodeableConcept
                    codeableConcept={resource.status}
                    name='Status'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='status'
                />
            }
            {
                resource.statusDate &&
                <Partials.DateTime
                    dateTime={resource.statusDate}
                    name='Status Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='status-date'
                />
            }
            {
                resource.containedItemQuantity &&
                <Partials.Quantity
                    quantity={resource.containedItemQuantity}
                    name='Contained Item Quantity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='contained-item-quantity'
                />
            }
            {
                resource.description &&
                <Partials.Markdown
                    markdown={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.characteristic &&
                <Partials.CodeableConcept
                    codeableConcept={resource.characteristic}
                    name='Characteristic'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='characteristic'
                />
            }
            {
                resource.copackagedIndicator &&
                <Partials.Boolean
                    boolean={resource.copackagedIndicator}
                    name='Copackaged Indicator'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='copackaged-indicator'
                />
            }
            {
                resource.manufacturer &&
                <Partials.Reference
                    reference={resource.manufacturer}
                    name='Manufacturer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='manufacturer'
                />
            }
        </>
    );
};

export default PackagedProductDefinition;
