/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_components so do not edit manually

/**
PaymentReconciliation
    This resource provides the details including amount of a payment and allocates
    the payment items being paid.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { Typography } from '@mui/material';
import { TPaymentReconciliation } from '../../types/resources/PaymentReconciliation';

// Import all the partial resource
import Partials from '../../partials';
import { SecurityTagSystem } from '../../utils/securityTagSystem';
import { generateUuidV5, isUuid } from '../../utils/uid.util';

const PaymentReconciliation = ({ resource }: { resource: TPaymentReconciliation }): React.ReactElement => {
    const sourceAssigningAuthority = resource?.meta?.security?.find(
        s => s.system === SecurityTagSystem.sourceAssigningAuthority
    )?.code;
    const uuid = resource.id && isUuid(`${resource.id}`) ?
        resource.id : generateUuidV5(`${resource.id}|${sourceAssigningAuthority}`);

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.period &&
                <Partials.Period
                    period={resource.period}
                    name='Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='period'
                />
            }
            {
                resource.created &&
                <Partials.DateTime
                    dateTime={resource.created}
                    name='Created'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='created'
                />
            }
            {
                resource.paymentIssuer &&
                <Partials.Reference
                    reference={resource.paymentIssuer}
                    name='Payment Issuer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment-issuer'
                />
            }
            {
                resource.request &&
                <Partials.Reference
                    reference={resource.request}
                    name='Request'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='request'
                />
            }
            {
                resource.requestor &&
                <Partials.Reference
                    reference={resource.requestor}
                    name='Requestor'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='requestor'
                />
            }
            {
                resource.outcome &&
                <Partials.Code code={resource.outcome} name='Outcome'/>
            }
            {
                resource.paymentAmount &&
                <Partials.Money
                    money={resource.paymentAmount}
                    name='Payment Amount'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment-amount'
                />
            }
            {
                resource.paymentIdentifier &&
                <Partials.Identifier
                    identifier={resource.paymentIdentifier}
                    name='Payment Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment-identifier'
                />
            }
            {
                resource.formCode &&
                <Partials.CodeableConcept
                    codeableConcept={resource.formCode}
                    name='Form Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='form-code'
                />
            }
        </>
    );
};

export default PaymentReconciliation;
