/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_components so do not edit manually

/**
Provenance
    Provenance of a resource is a record that describes entities and processes
    involved in producing and delivering or otherwise influencing that resource.
    Provenance provides a critical foundation for assessing authenticity, enabling
    trust, and allowing reproducibility. Provenance assertions are a form of
    contextual metadata and can themselves become important records with their own
    provenance. Provenance statement indicates clinical significance in terms of
    confidence in authenticity, reliability, and trustworthiness, integrity, and
    stage in lifecycle (e.g. Document Completion - has the artifact been legally
    authenticated), all of which may impact security, privacy, and trust policies.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { Typography } from '@mui/material';
import { TProvenance } from '../../types/resources/Provenance';

// Import all the partial resource
import Partials from '../../partials';
import { SecurityTagSystem } from '../../utils/securityTagSystem';
import { generateUuidV5, isUuid } from '../../utils/uid.util';

const Provenance = ({ resource }: { resource: TProvenance }): React.ReactElement => {
    const sourceAssigningAuthority = resource?.meta?.security?.find(
        s => s.system === SecurityTagSystem.sourceAssigningAuthority
    )?.code;
    const uuid = resource.id && isUuid(`${resource.id}`) ?
        resource.id : generateUuidV5(`${resource.id}|${sourceAssigningAuthority}`);

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.target &&
                <Partials.Reference
                    reference={resource.target}
                    name='Target'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='target'
                />
            }
            {
                resource.occurredPeriod &&
                <Partials.Period
                    period={resource.occurredPeriod}
                    name='Occurred Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='occurred-period'
                />
            }
            {
                resource.occurredDateTime &&
                <Partials.DateTime
                    dateTime={resource.occurredDateTime}
                    name='Occurred Date Time'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='occurred-date-time'
                />
            }
            {
                resource.recorded &&
                <Partials.Instant
                    instant={resource.recorded}
                    name='Recorded'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='recorded'
                />
            }
            {
                resource.policy &&
                <Partials.Uri
                    uri={resource.policy}
                    name='Policy'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='policy'
                />
            }
            {
                resource.location &&
                <Partials.Reference
                    reference={resource.location}
                    name='Location'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='location'
                />
            }
            {
                resource.reason &&
                <Partials.CodeableConcept
                    codeableConcept={resource.reason}
                    name='Reason'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reason'
                />
            }
            {
                resource.activity &&
                <Partials.CodeableConcept
                    codeableConcept={resource.activity}
                    name='Activity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='activity'
                />
            }
            {
                resource.agent &&
                <Partials.Reference
                    reference={resource.agent}
                    name='Agent'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='agent'
                    field='who'
                />
            }
            {
                resource.entity &&
                <Partials.Reference
                    reference={resource.entity}
                    name='Entity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='entity'
                    field='what'
                />
            }
            {
                resource.signature &&
                <Partials.Reference
                    reference={resource.signature}
                    name='Signature'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='signature'
                    field='who'
                />
            }
        </>
    );
};

export default Provenance;
