/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_components so do not edit manually

/**
SupplyDelivery
    Record of delivery of what is supplied.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router-dom';
import { TSupplyDelivery } from '../../types/resources/SupplyDelivery';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const SupplyDelivery = ({ resource }: { resource: TSupplyDelivery }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.basedOn &&
                <Partials.Reference
                    reference={resource.basedOn}
                    name='Based On'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='based-on'
                />
            }
            {
                resource.partOf &&
                <Partials.Reference
                    reference={resource.partOf}
                    name='Part Of'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='part-of'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.patient &&
                <Partials.Reference
                    reference={resource.patient}
                    name='Patient'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='patient'
                />
            }
            {
                resource.type &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.occurrenceDateTime &&
                <Partials.DateTime
                    dateTime={resource.occurrenceDateTime}
                    name='Occurrence Date Time'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='occurrence-date-time'
                />
            }
            {
                resource.occurrencePeriod &&
                <Partials.Period
                    period={resource.occurrencePeriod}
                    name='Occurrence Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='occurrence-period'
                />
            }
            {
                resource.occurrenceTiming &&
                <Partials.Timing
                    timing={resource.occurrenceTiming}
                    name='Occurrence Timing'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='occurrence-timing'
                />
            }
            {
                resource.supplier &&
                <Partials.Reference
                    reference={resource.supplier}
                    name='Supplier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='supplier'
                />
            }
            {
                resource.destination &&
                <Partials.Reference
                    reference={resource.destination}
                    name='Destination'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='destination'
                />
            }
            {
                resource.receiver &&
                <Partials.Reference
                    reference={resource.receiver}
                    name='Receiver'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='receiver'
                />
            }
        </>
    );
};

export default SupplyDelivery;
