/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

import { TId } from '../simpleTypes/Id';
import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TPeriod } from '../partials/Period';
import { TDateTime } from '../simpleTypes/DateTime';
import { TClaimRelated } from '../partials/ClaimRelated';
import { TClaimPayee } from '../partials/ClaimPayee';
import { TClaimCareTeam } from '../partials/ClaimCareTeam';
import { TClaimSupportingInfo } from '../partials/ClaimSupportingInfo';
import { TClaimDiagnosis } from '../partials/ClaimDiagnosis';
import { TClaimProcedure } from '../partials/ClaimProcedure';
import { TClaimInsurance } from '../partials/ClaimInsurance';
import { TClaimAccident } from '../partials/ClaimAccident';
import { TClaimItem } from '../partials/ClaimItem';
import { TMoney } from '../partials/Money';

export type TClaim = {
    resourceType?: String;
    id?: TId;
    meta?: TMeta;
    implicitRules?: TUri;
    language?: String;
    text?: TNarrative;
    contained?: TResourceContainer[];
    extension?: TExtension[];
    modifierExtension?: TExtension[];
    identifier?: TIdentifier[];
    status: String;
    type: TCodeableConcept;
    subType?: TCodeableConcept;
    use: String;
    patient: TReference;
    billablePeriod?: TPeriod;
    created: TDateTime;
    enterer?: TReference;
    insurer?: TReference;
    provider: TReference;
    priority: TCodeableConcept;
    fundsReserve?: TCodeableConcept;
    related?: TClaimRelated[];
    prescription?: TReference;
    originalPrescription?: TReference;
    payee?: TClaimPayee;
    referral?: TReference;
    facility?: TReference;
    careTeam?: TClaimCareTeam[];
    supportingInfo?: TClaimSupportingInfo[];
    diagnosis?: TClaimDiagnosis[];
    procedure?: TClaimProcedure[];
    insurance: TClaimInsurance[];
    accident?: TClaimAccident;
    item?: TClaimItem[];
    total?: TMoney;
};

